### ISSUE TITLE
MSFT_SecurityOption: Spelling error in MSFT_SecurityOption.psm1

### ISSUE THREAD

**Issue by swspoerle** [PowerShell/SecurityPolicyDsc#105]
#### Details of the scenario you tried and the problem that is occurring
The ValidateSet in the Parameter for User_Account_Control_Behavior_of_the_elevation_prompt_for_standard_users has a misspelling of "Prompt for credentials" as it says "Prompt for crendentials"
#### Verbose logs showing the problem
`SecurityPolicyDsc\SecurityOption : At least one of the values 'Prompt for credentials' is not supported or valid for
property 'User_Account_Control_Behavior_of_the_elevation_prompt_for_standard_users' on class 'SecurityOption'. Please
specify only supported values:
Automatically deny elevation request, Prompt for credentials on the secure desktop, Prompt for crendentials.`
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
User_Account_Control_Behavior_of_the_elevation_prompt_for_standard_users
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.5.0.0

**Comment by jcwalker** [comment]
@swspoerle good catch on this.  I should be able to take of this within a week or so.
