### ISSUE TITLE
Request : SecurityTemplate include FileHash parameter

### ISSUE THREAD

**Issue by bdanse** [PowerShell/SecurityPolicyDsc#19]
From a security point of view, how do I know the file that is being imported is not modified. 
A filehash check would be a nice addition to this great module. 

For example run get-filehash against "C:\scratch\SecurityPolicyBackup.inf". And include the Hash result in the resource.

Configuration

 CompareInfs
{
    Import-DscResource -ModuleName SecurityPolicyDsc

    node localhost
    {
        SecurityTemplate TrustedCredentialAccess
        {
            Path = "C:\scratch\SecurityPolicyBackup.inf"
            IsSingleInstance = 'Yes'
	    FileHash = '9A7C892496CFAA5CF8CC2BDDCC255E15CEDF95997F87FF8913E5DB7EB17A006B'
        }
    }
}

CompareInfs -OutputPath C:\DSC
Start-DscConfiguration -Path C:\DSC -Wait -Verbose -Force

**Comment by zjalexander** [comment]
discussion is at https://github.com/PowerShell/GPRegistryPolicy/issues/2

**Comment by athaynes** [comment]
@zjalexander Can we also close this issue based on the conversation at https://github.com/PowerShell/GPRegistryPolicy/issues/2

**Comment by zjalexander** [comment]
also yes :)
