### ISSUE TITLE
SecurityTemplate bug

### ISSUE THREAD

**Issue by mtrog** [PowerShell/SecurityPolicyDsc#29]
There is a potential issue within the DSCResource "SecurityTemplate" - 

In the function "ConvertTo-LocalFriendlyName" found in SecurityPolicyResourceHelper.psm1.
Line 165 of SecurityPolicyResourceHelper.psm1 says:
"if ($null -ne $id -and $id -match 'S-')"

There are Security settings that can match this statement but not be a System.Security.Principal.SecurityIdentifier.  A good example of this is the logon banner - Registry key 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\LegalNoticeText'.  If The logon Banner contains S-, the script tries (and fails) to convert it.

**Comment by jcwalker** [comment]
@mtrog have you ran into this? If so can you provide detailed repo steps? ConvertTo-LocalFriendlyName will only address arguments that are Identities of user rights assignments.  If you have a repo where this isn't the case please let me know.

**Comment by nlsdg** [comment]
This has been fixed by PR #36. Please check with a current release.
