### ISSUE TITLE
Invoke-Secedit issue

### ISSUE THREAD

**Issue by mtrog** [PowerShell/SecurityPolicyDsc#30]
If the path passed to invoke-secedit contains special characters ('{' or '}' specifically), the secedit command fails. 

To fix, $userRightsToAddInf should be surrounded by escaped quotes (or something similar) - Line 89 of SecurityPolicyResourceHelper.psm1.

**Comment by jcwalker** [comment]
Hi @mtrog can you provide repo steps?  $userRightToAddInf is assigned privately and can't be changed from the configuration script.
