### ISSUE TITLE
ConvertTo-LocalFriendlyName incorrectly handles user or group names containing 'S-'

### ISSUE THREAD

**Issue by BernieWhite** [PowerShell/SecurityPolicyDsc#35]
User or group accounts that contain __S-__ in their name are incorrectly treated as a SID and translated.

Translation fails with a warning similar to the following.

> WARNING: Error processing user-s-1. Error message: Cannot convert value "user-s-1" to type "System.Security.Principal.SecurityIdentifier". Error: "Value was invalid.

The issue occurs because the regular expression `($null -ne $id -and $id -match 'S-')` matches any part of the string, instead of the beginning.

**Comment by BernieWhite** [comment]
@jcwalker  Ah, how would this actually fix the issue?

**Comment by hackjammer** [comment]
Can you please merge this to master / push to PSGallery?

We're relying on this module and PSGallery as part of our DSC pipeline and the current PSGallery version has some serious bugs fixed by these commits that make it unusable.

Thanks!
