### ISSUE TITLE
DomainControllerSecurityOptions

### ISSUE THREAD

**Issue by BernieWhite** [PowerShell/SecurityPolicyDsc#41]
If nobody has started working on something simular I would like to add a _DomainControllerSecurityOptions_ resource to configure the _Domain Controller:_ marked settings within Local Policies > Security Options of the Local Security Policy.

My approach would be to provide named properties as a IsSingleInstance resource to each setting, and use a ValidateSet for each option to provide mapping to experience exposed in the Local Security Policy UI.

**Comment by jcwalker** [comment]
Closing this issue because the functionality specified already exists
