### ISSUE TITLE
UserRightsAssignement

### ISSUE THREAD

**Issue by nofate301** [PowerShell/SecurityPolicyDsc#42]
Was using this with Azure DSC.  Server 2012R2 VM.  It worked perfectly, but Azure reported that nothing was compliant even though I reviewed and confirmed the rights had been assigned correctly.

Not sure if there is something at issue with the Resource or Azure, but it was very confusing.

**Comment by nofate301** [comment]
This is also happening with Azure's 2008 HUB image.  Everything looks good after application, but Azure is reporting the following on each item.

`{
    "Exception":  {
                      "Message":  "PowerShell DSC resource MSFT_UserRightsAssignment  failed to execute Set-TargetResource functionality with error message: Task did not complete successfully See log %windir%\\security\\logs\\scesrv.log for detail info. ",
                      "Data":  {

                               },
                      "InnerException":  {
                                             "ErrorRecord":  "Task did not complete successfully See log %windir%\\security\\logs\\scesrv.log for detail info.",
                                             "WasThrownFromThrowStatement":  true,
                                             "Message":  "Task did not complete successfully See log %windir%\\security\\logs\\scesrv.log for detail info.",
                                             "Data":  "System.Collections.ListDictionaryInternal",
                                             "InnerException":  "System.Management.Automation.RuntimeException: Task did not complete successfully See log %windir%\\security\\logs\\scesrv.log for detail info.",
                                             "TargetSite":  "System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)",
                                             "StackTrace":  "   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)\r\n   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)\r\n   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)\r\n   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)\r\n   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32\u0026 resultStatusHandle, Collection`1\u0026 result, ErrorRecord\u0026 errorRecord, PSModuleInfo localRunSpaceModuleInfo)",
                                             "HelpLink":  null,
                                             "Source":  "System.Management.Automation",
                                             "HResult":  -2146233087
                                         },
                      "TargetSite":  null,
                      "StackTrace":  null,
                      "HelpLink":  null,
                      "Source":  null,
                      "HResult":  -2146233079
                  },
    "TargetObject":  null,
    "CategoryInfo":  {
                         "Category":  7,
                         "Activity":  "",
                         "Reason":  "InvalidOperationException",
                         "TargetName":  "",
                         "TargetType":  ""
                     },
    "FullyQualifiedErrorId":  "ProviderOperationExecutionFailure",
    "ErrorDetails":  null,
    "InvocationInfo":  null,
    "ScriptStackTrace":  null,
    "PipelineIterationInfo":  [

                              ]
}`

The log mentioned shows no errors at least as far as I can see.

-------------------------------------------
Monday, July 03, 2017 8:00:01 PM
----Configuration engine was initialized successfully.----

----Reading Configuration Template info...


----Configure User Rights...
		SeImpersonatePrivilege must be assigned to administrators. This setting is adjusted.
		SeImpersonatePrivilege must be assigned to SERVICE. This setting is adjusted.
	Configure S-1-5-20.
	Configure S-1-5-19.
	Configure S-1-5-32-551.
	Configure S-1-5-32-544.
	Configure S-1-5-32-559.
	Configure S-1-5-32-545.
	Configure S-1-1-0.
	Configure S-1-5-6.
	Configure S-1-5-7.
	Configure S-1-5-32-546.
	Configure S-1-5-32-547.
	Configure S-1-5-11.
	Configure S-1-5-32-555.
	Configure S-1-5-80-0.
	Configure S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420.

	User Rights configuration was completed successfully.


----Configure Group Membership...

	Group Membership configuration was completed successfully.


----Configure 64-bit Registry Keys...

	Configuration of Registry Keys was completed successfully.


----Configure 32-bit Registry Keys...


----Configure File Security...

	File Security configuration was completed successfully.


----Configure General Service Settings...

	General Service configuration was completed successfully.


----Configure available attachment engines...

	Configuration of attachment engines was completed successfully.


----Configure Security Policy...
	Configure password information.

	System Access configuration was completed successfully.

	Configuration of Registry Values was completed successfully.
Legacy audit settings are disabled. Skipped configuration of legacy audit settings.

	Audit/Log configuration was completed successfully.


----Configure available attachment engines...

	Configuration of attachment engines was completed successfully.


----Un-initialize configuration engine...

**Comment by jcwalker** [comment]
@nofate301 can you provide an example of the property values for the UserRightsAssignment resource?
Is the identities you are assigning the policy to local or domain accounts?

**Comment by nofate301** [comment]
below are some of the configuration nodes.

UserRightsAssignment Access_this_computer_from_the_network
{
Identity = '*S-1-5-32-551','*S-1-5-32-544','*S-1-5-11'
Policy = 'Access_this_computer_from_the_network'
Ensure = 'Present'
Force = $True
}

UserRightsAssignment Adjust_memory_quotas_for_a_process
{
Identity = '*S-1-5-32-544','*S-1-5-20','*S-1-5-19'
Policy = 'Adjust_memory_quotas_for_a_process'
Ensure = 'Present'
Force = $True
}

**Comment by jcwalker** [comment]
@nofate301 I think I found the issue.  The asterisk in front of the SID is not being taken into account during Test-TargetResource but if I removed the asterisk Set-TargetResource would fail. So we need to add the code to handle that scenario.  There is a similar issue (#33) opened by @Stangg187.  The Test-TargetResource fails because of the computer name in front of the local user ex. (localhost\TestUser1).  If the computer name is removed from the local user everything works fine.

**Comment by nofate301** [comment]
I'll yank the asterix from my config and give that a shot.  Again, the
configuration took, Azure just reported non-compliance.

**Comment by jcwalker** [comment]
@nofate301 I added the code to fix your issue to the dev branch.  Can you test the code in the dev branch to confirm or deny the fix?

**Comment by nofate301** [comment]
Ok so, I pulled the asterix and attempted to use what was there.  I got locked out of the server and could not log in.  I managed to pull the log through some luck and re-gain access by using the configuration with the asterix.

`-------------------------------------------
Friday, July 7, 2017 4:12:30 PM
----Configuration engine was initialized successfully.----

----Reading Configuration Template info...


----Configure User Rights...
		SeImpersonatePrivilege must be assigned to administrators. This setting is adjusted.
		SeImpersonatePrivilege must be assigned to SERVICE. This setting is adjusted.
	Configure S-1-5-20.
		remove SeIncreaseQuotaPrivilege.
Error 50: The request is not supported.
 Configuring some user rights for this account is not supported. Re-attempting configuration by ignoring unsupported operation errors.
		remove SeIncreaseQuotaPrivilege.
Configuring SeIncreaseQuotaPrivilege for this account is not supported.
	Configure S-1-5-19.
		remove SeIncreaseQuotaPrivilege.
Error 50: The request is not supported.
 Configuring some user rights for this account is not supported. Re-attempting configuration by ignoring unsupported operation errors.
		remove SeIncreaseQuotaPrivilege.
Configuring SeIncreaseQuotaPrivilege for this account is not supported.
	Configure S-1-5-32-551.
	Configure S-1-5-32-544.
		remove SeIncreaseQuotaPrivilege.
	Configure S-1-5-32-559.
	Configure S-1-5-32-545.
	Configure S-1-1-0.
	Configure S-1-5-6.
	Configure S-1-5-7.
	Configure S-1-5-32-546.
	Configure S-1-5-32-544.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-544.
	Configure S-1-5-20.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-20.
	Configure S-1-5-19.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-19.
	Configure S-1-5-32-547.
	Configure S-1-5-32-551.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-551.
	Configure S-1-5-11.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-11.
	Configure S-1-5-32-555.
	Configure S-1-5-80-0.
	Configure S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420.

	User Rights configuration was completed with one or more errors.


----Configure Group Membership...

	Group Membership configuration was completed successfully.


----Configure 64-bit Registry Keys...

	Configuration of Registry Keys was completed successfully.


----Configure 32-bit Registry Keys...


----Configure File Security...

	File Security configuration was completed successfully.


----Configure General Service Settings...

	General Service configuration was completed successfully.


----Configure available attachment engines...

	Configuration of attachment engines was completed successfully.


----Configure Security Policy...
	Configure password information.

	System Access configuration was completed successfully.

	Configuration of Registry Values was completed successfully.

	Audit/Log configuration was completed successfully.


----Configure available attachment engines...

	Configuration of attachment engines was completed successfully.


----Un-initialize configuration engine...
`

Seems those asterix are necessary. 


I tried to upload the dev branch to Azure and use that, but I got several errors when attempting this.  Azure couldn't extract the module due to an error with the content of the zip file.

**Comment by jcwalker** [comment]
@nofate301 yes I'm experiencing the same, the asterisks are required.  The dev branch should fix run without errors now when an asterisks is included with a SID

**Comment by nofate301** [comment]
Here's the error I receive when trying to upload the zip file of the dev branch to Azure

Error extracting the activities from module SecurityPolicyDsc. Extraction failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

**Comment by jcwalker** [comment]
@nofate301 Hmm...I am able to successfully import every module in SecurityPolicyDsc.  Is folder name inside the zip SecuirtyPolicyDsc-dev?  If so rename it to simply SecurityPolicyDsc.

**Comment by nofate301** [comment]
Alright, got it imported, I changed the folder name.

I tried with a configuration without Asterix, and the log puked

`-------------------------------------------
Friday, July 7, 2017 5:09:45 PM
----Configuration engine was initialized successfully.----

----Reading Configuration Template info...


----Configure User Rights...
		SeInteractiveLogonRight must be assigned to administrators. This setting is adjusted.
		SeImpersonatePrivilege must be assigned to administrators. This setting is adjusted.
		SeImpersonatePrivilege must be assigned to SERVICE. This setting is adjusted.
		Error assigning SeSystemtimePrivilege to Administrators account. This setting may block administrators from logging on interactively.
	Configure S-1-5-20.
		remove SeChangeNotifyPrivilege.
		remove SeAuditPrivilege.
		remove SeIncreaseQuotaPrivilege.
		remove SeAssignPrimaryTokenPrivilege.
		remove SeImpersonatePrivilege.
		remove SeCreateGlobalPrivilege.
Error 50: The request is not supported.
 Configuring some user rights for this account is not supported. Re-attempting configuration by ignoring unsupported operation errors.
		remove SeChangeNotifyPrivilege.
Configuring SeChangeNotifyPrivilege for this account is not supported.
		remove SeAuditPrivilege.
Configuring SeAuditPrivilege for this account is not supported.
		remove SeIncreaseQuotaPrivilege.
Configuring SeIncreaseQuotaPrivilege for this account is not supported.
		remove SeAssignPrimaryTokenPrivilege.
Configuring SeAssignPrimaryTokenPrivilege for this account is not supported.
		remove SeImpersonatePrivilege.
Configuring SeImpersonatePrivilege for this account is not supported.
		remove SeCreateGlobalPrivilege.
Configuring SeCreateGlobalPrivilege for this account is not supported.
	Configure S-1-5-20.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-20.
	Configure S-1-5-19.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-19.
	Configure S-1-5-32-551.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-551.
	Configure S-1-5-32-544.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-544.
	Configure S-1-5-32-559.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-559.
	Configure S-1-5-32-545.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-545.
	Configure S-1-1-0.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-1-0.
	Configure S-1-5-6.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-6.
	Configure S-1-5-7.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-7.
	Configure S-1-5-32-546.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-546.
	Configure S-1-5-32-547.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-547.
	Configure S-1-5-11.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-11.
	Configure S-1-5-32-555.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-32-555.
	Configure S-1-5-80-0.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-80-0.
	Configure S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420.
Error 1332: No mapping between account names and security IDs was done.
 	Cannot find S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420.
	Configure S-1-5-32-544.
		remove SeTakeOwnershipPrivilege.
	Configure S-1-5-6.
	Configure S-1-5-19.
		remove SeChangeNotifyPrivilege.
		remove SeAuditPrivilege.
		remove SeIncreaseQuotaPrivilege.
		remove SeAssignPrimaryTokenPrivilege.
		remove SeImpersonatePrivilege.
		remove SeCreateGlobalPrivilege.
		remove SeTimeZonePrivilege.
Error 50: The request is not supported.
 Configuring some user rights for this account is not supported. Re-attempting configuration by ignoring unsupported operation errors.
		remove SeChangeNotifyPrivilege.
Configuring SeChangeNotifyPrivilege for this account is not supported.
		remove SeAuditPrivilege.
Configuring SeAuditPrivilege for this account is not supported.
		remove SeIncreaseQuotaPrivilege.
Configuring SeIncreaseQuotaPrivilege for this account is not supported.
		remove SeAssignPrimaryTokenPrivilege.
Configuring SeAssignPrimaryTokenPrivilege for this account is not supported.
		remove SeImpersonatePrivilege.
Configuring SeImpersonatePrivilege for this account is not supported.
		remove SeCreateGlobalPrivilege.
Configuring SeCreateGlobalPrivilege for this account is not supported.
		remove SeTimeZonePrivilege.
Configuring SeTimeZonePrivilege for this account is not supported.

	User Rights configuration was completed with one or more errors.


----Configure Group Membership...

	Group Membership configuration was completed successfully.


----Configure 64-bit Registry Keys...

	Configuration of Registry Keys was completed successfully.


----Configure 32-bit Registry Keys...


----Configure File Security...

	File Security configuration was completed successfully.


----Configure General Service Settings...

	General Service configuration was completed successfully.


----Configure available attachment engines...

	Configuration of attachment engines was completed successfully.


----Configure Security Policy...
	Configure password information.

	System Access configuration was completed successfully.

	Configuration of Registry Values was completed successfully.

	Audit/Log configuration was completed successfully.


----Configure available attachment engines...

	Configuration of attachment engines was completed successfully.


----Un-initialize configuration engine...
`

I'm going to try a configuration with the asterix and see what I get.

**Comment by nofate301** [comment]
Got it uploaded.  The configuration without an asterix errors out hard and appears to remove all the rights that I set and pretty much denies all access to the host.

When I apply
UserRightsAssignment Access_this_computer_from_the_network
{
Identity = '*S-1-5-32-551','*S-1-5-32-544','*S-1-5-11'
Policy = 'Access_this_computer_from_the_network'
Ensure = 'Present'
Force = $True
}
I get
![image](https://user-images.githubusercontent.com/24656618/27972673-2abfb0ee-6325-11e7-8db7-bb799f56237e.png)

If I use the configuration without an asterix
UserRightsAssignment Access_this_computer_from_the_network
{
Identity = 'S-1-5-32-551','S-1-5-32-544','S-1-5-11'
Policy = 'Access_this_computer_from_the_network'
Ensure = 'Present'
Force = $True
}
I get
![image](https://user-images.githubusercontent.com/24656618/27972714-505820c0-6325-11e7-9dc3-6fd6381ead6b.png)

Both show up in Azure as failed/non-compliant, but it looks good.  So it's possible my asterix is working, but maybe a part of it isn't applying fully.  So like a right that i've chosen isn't assignable.

**Comment by jcwalker** [comment]
@nofate301  Does Azure show the VM is non-compliant because of that resource?  Is there another resource in your configuration script? When I run the following:
``` PowerShell
configuration TestUSR
{
    Import-DscResource -ModuleName SecurityPolicyDsc

    node localhost
    {
        UserRightsAssignment Access_this_computer_from_the_network
        {
            Identity = '*S-1-5-32-551','*S-1-5-32-544','*S-1-5-11'
            Policy = 'Access_this_computer_from_the_network'
            Ensure = 'Present'
            Force = $True
        }
    }
}

TestUsr -OutputPath c:\Dsc 

Start-DscConfiguration -Path c:\dsc -Verbose -Wait -Force
```
The configuration completes without error.

**Comment by nofate301** [comment]
Here's a screenshot of well, everything

![image](https://user-images.githubusercontent.com/24656618/27975133-f5e3e48a-632e-11e7-987b-c024c446aab5.png)

**Comment by jcwalker** [comment]
It's like the VM or Azure is still using the old code.

**Comment by nofate301** [comment]
Maybe it is.  I'd have to upload the module manually to the server in question I believe to get this working.  I mean, my guess is the import function can't call the dev branch.
