### ISSUE TITLE
Overwrite Values

### ISSUE THREAD

**Issue by sam-cogan** [PowerShell/SecurityPolicyDsc#43]
Is there a way to have this resource apply exactly what you define in the DSC file? It seems at the moment even when using the "force" flag it still appends to existing values rather than overwriting. For example, trying to set "Bypass Traverse Checking" to what is defined in the MS security baseline, which does not include the everyone group, still results in the everyone group being present.
This seems to run contrary to the belief that a DSC file should represent exactly what the configuration should be on the node.

**Comment by jcwalker** [comment]
Hi @sam-cogan There is a Force parameter on the UserRightsAssignment resource that will apply the exact identities.
``` PowerShell
        UserRightsAssignment 'Bypass_traverse_checking'
        {
            Identity = "*S-1-5-19","*S-1-5-20","*S-1-5-32-544","*S-1-5-32-545","*S-1-5-32-551","*S-1-5-90-0"
            Policy = 'Bypass_traverse_checking'
            Ensure = 'Present'
            Force = $True
        }
```

**Comment by sam-cogan** [comment]
That's my point, I am using the Force parameter, but it doesn't work as I expect, it doesn't replace the current values, it appends. If the force parameter is supposed to work in that way then I need to look more into why the end result differs from what is expected. Thanks.
