### ISSUE TITLE
Facing issue in DSC script for xSQLServerDatabase resource compiling in Azure under Automation (DSC Configuration)

### ISSUE THREAD

**Issue by Fuzail92** [PowerShell/SecurityPolicyDsc#57]
Error:
Exception calling "NewScriptBlock" with "1" argument(s): "At line:5 char:1
+ Import-DscResource -ModuleName xSQLServerDatabase
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Could not find the module 'xSQLServerDatabase'.

 At line:11 char:6
+ xSQLServerDatabase Create_Database
+ ~~~~~~~~~~~~~~~~~~ Undefined DSC resource 'xSQLServerDatabase'. Use Import-DSCResource to import the resource." (At line:5 char:1
+ Import-DscResource -ModuleName xSQLServerDatabase
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Could not find the module 'xSQLServerDatabase'.

 At line:11 char:6
+ xSQLServerDatabase Create_Database
+ ~~~~~~~~~~~~~~~~~~ Undefined DSC resource 'xSQLServerDatabase'. Use Import-DSCResource to import the resource.)

**Comment by jcwalker** [comment]
@Fuzail92 did you intend to post this to the SecurityPolicyDsc repo?
