### ISSUE TITLE
Spelling Error in AccountPolicy resource

### ISSUE THREAD

**Issue by aydeisen** [PowerShell/SecurityPolicyDsc#60]
I know it's a minor change with a major impact to anyone using version 2.0.0.0, but can the spelling for '**Enfore**_user_logon_restrictions' be corrected to '**Enforce**_user_login_restrictions'?

**Comment by jcwalker** [comment]
@aydeisen good catch. The dev branch has been updated.

**Comment by aydeisen** [comment]
Thank you.  One more under the Security Option resource:

Interactive_logon_Require_Domain_Controller_authenticatio_to_unlock_workstation should be Interactive_logon_Require_Domain_Controller_authentication_to_unlock_workstation

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
