### ISSUE TITLE
Network_security_Configure_encryption_types_allowed_for_Kerberos

### ISSUE THREAD

**Issue by stephensmalls** [PowerShell/SecurityPolicyDsc#66]
I noticed that this SecurityOption does not allow for 'Future encryption types' to be selected.

```
    "Network_security_Configure_encryption_types_allowed_for_Kerberos" = @{    
        Value   = "MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters\SupportedEncryptionTypes"
        Section = 'Registry Values'
        Option  = @{
            DES_CBC_CRC  = '4,1'
            DES_CBC_MD5  = '4,2'
            RC4_HMAC_MD5 = '4,4'
            AES128_HMAC_SHA1  = '4,8'
            AES256_HMAC_SHA1  = '4,16'           
        }
    } 

```

But this article from Microsoft explains how to enable that setting.
[(https://blogs.technet.microsoft.com/petergu/2013/04/14/interpreting-the-supportedencryptiontypes-registry-key/)]

Any plans to include this setting?

**Comment by jcwalker** [comment]
Hi @stephensmalls no plans at this time.  If there is a high demand for this we can include it in the future.

**Comment by russelltomkins** [comment]
Can we please re-open this one? I've completed the modifications and happy to provide the details in a PR. I've worked with many customers where misconfiguring this setting causes major issues. If MS does add a new EType, this could cause a lot of future support cases.

**Comment by johlju** [comment]
Sure, thank you for contributing. Labeling it as an enhancement as in progress.
