### ISSUE TITLE
Import from Azure Automation Gallery Missing resources

### ISSUE THREAD

**Issue by Safetybrick** [PowerShell/SecurityPolicyDsc#75]
Imported the latest version (2.1.0.0) of the resource from the gallery which displays all of the resources but once imported under the Automation account only AccountPolicy is displayed.

**Comment by johlju** [comment]
The same problem occurs for SqlServerDsc. But the the resources can still be used to compile configurations. Even if they are not are shown, please try to use them.

**Comment by Safetybrick** [comment]
Thanks johlju, i put together a test configuration and they worked.
