### ISSUE TITLE
"." appears to break SecurityOption

### ISSUE THREAD

**Issue by mattanguige** [PowerShell/SecurityPolicyDsc#79]
An error is presented when attempting to set the "Network_security_LAN_Manager_authentication_level" SecurityOption to either "Send NTLMv2 response only. Refuse LM" or "Send NTLMv2 response only. Refuse LM & NTLM". All other available values (without the "." character) appear to work correctly, so I believe this is an issue with the "." being stripped out somewhere.

**Comment by jcwalker** [comment]
Hi @mattanguige  I have ran the following configuration in my lab and it works as expected.  Can you provide an example of the configuration that errors?

configuration NetworkSecurity
{
    Import-DscResource -ModuleName SecurityPolicyDsc

    node localhost
    {
        SecurityOption NetworkSecurity
        {
            Name = 'NetworkSecurity'
            Network_security_LAN_Manager_authentication_level = 'Send NTLMv2 responses only. Refuse LM & NTLM'
        }
    }
}

**Comment by johlju** [comment]
Closing this as lack of response so assumed answered by previous comment. If this was closed in error, then please reopen or comment.

**Comment by mattanguige** [comment]
Apologies, I've been unable to revisit this recently. This must have been an issue with our configuration, I had to comment out that line and use the Registry resource for that setting. Hopefully I'll revisit this another day.
