### ISSUE TITLE
Define acceptable values

### ISSUE THREAD

**Issue by ewhitesides** [PowerShell/SecurityPolicyDsc#80]
Many of the policy settings have Parameters that simply just accept [string], so as the user of this module I'm not sure what I should be putting in as the string to Enable/Disable a setting.

**Comment by jcwalker** [comment]
@ewhitesides are you referring to policies in SecurityOption?

**Comment by johlju** [comment]
I think the README.md should atleast be update to cleary show the possible values for each parameter. I had to look a couple of times and referencing the schema.mof before understanding that the values under here was actually parameters and not values; https://github.com/PowerShell/SecurityPolicyDsc#for-explanation-of-below-settings-please-consult-security-policy-reference

**Comment by johlju** [comment]
Propose using the format 
```markdown
* **`[String]` Accounts_Guest_account_status** _(Write)_:  { *Disabled* | Enabled | Value3 | ...etc...  }
* **`[String]` Accounts_Rename_guest_account** _(Write)_:  The name of the account to use for guests.
```
The value in *italic* is the default value.
