### ISSUE TITLE
Account Policy errors

### ISSUE THREAD

**Issue by ewhitesides** [PowerShell/SecurityPolicyDsc#81]
The following settings in AccountPolicy seem to be defined by the Default Domain GPO policy already, so you get an error when you try to define them in DSC on a domain connected computer.  Perhaps this should mentioned somehow in an example for clarification?

Enforce_user_logon_restrictions
Maximum_lifetime_for_service_ticket
Maximum_lifetime_for_user_ticket
Maximum_lifetime_for_user_ticket_renewal
Maximum_tolerance_for_computer_clock_synchronization

**Comment by jcwalker** [comment]
readme has been updated, and an example with Kerberos policy settings has been added.

**Comment by ewhitesides** [comment]
If I have 2 domain controllers, and many member servers, would I push this to only one DC, both DC, or all servers in my environment?
