### ISSUE TITLE
"Network_access_Remotely_accessible_registry_paths_and_subpaths" Add multiple paths

### ISSUE THREAD

**Issue by Stachows** [PowerShell/SecurityPolicyDsc#83]
I am relatively new to DSC but have found ALOT of my answers here in the DOCS and on the web.

But, one issue has me stumped.
I need to add MULTIPLE paths to the "Security Option" "Network_access_Remotely_accessible_registry_paths_and_subpaths"

I can add one path, and only 1 path, no matter how I try.  I have tried setting using the SecurityPolicyDsc resource (many different ways) and also straight up using the Registry Resource, Which fails miserable because an export of the data is hex, but when using DSC to add it back in, it just adds the hex data to the MultiString key...

I am at a loss.
I would prefer to us the SecurityPolicyDSC resource, but will use registry if that is my only way.

If anyone has figured this out, I would greatly appreciate your input!
Thanks!

**Comment by Stachows** [comment]
I actually found my own answer.  I created a .INF file to look at what it was looking for, and all i needed to do was separate the entries with a comma.  How frustrating for it to be so simple after many hours.

**Comment by Safetybrick** [comment]
I have run into a similar issue along with Network_access_Remotely_accessible_registry_paths which I need to apply multiple paths with. No luck in a solution yet.

**Comment by johlju** [comment]
The are not array is the schemo.mof or the code, so that won't work. They have to be changed to a string array and the code changed accordingly to support multiple paths (and array of paths).

https://github.com/PowerShell/SecurityPolicyDsc/blob/77e2594daf74c9e0c6305d9fc62e3f764a897dc1/DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.schema.mof#L59-L60

**Comment by heatherdaye** [comment]
I was able to set this via SecurityPolicy DSC with a single comma delimited string
Network_access_Remotely_accessible_registry_paths_and_subpaths = "path 1, path 2, path 3"

**Comment by johlju** [comment]
@heatherdaye Glad you found a solution to this!

@jcwalker is this the intended behavior, this property should not support an array? Just a comma separated list?

**Comment by jcwalker** [comment]
If the schema says it's just a string and not an array I guess it is the intended behavior.  It's been too long since I wrote it to remember the specifics.  I'm always open to change/improve it on what the community agrees is best.

**Comment by heatherdaye** [comment]
Originally I had assumed it would be an array of strings. When it only took the first string, I began trial and error. I would suggest changing this to an array of strings as that is what would be expected based on other settings in the module.

**Comment by johlju** [comment]
If it is changed to an array, and the resource builds a comma separated string, then both the following would work. 

```
Network_access_Remotely_accessible_registry_paths_and_subpaths = 'path 1, path 2, path 3'
```
```
Network_access_Remotely_accessible_registry_paths_and_subpaths = @('path 1', 'path 2', 'path 3')
```

That means that existing configurations would still work. Although, since it should return an array, it would be a breaking change for users expecting an comma separated string when running Get-DscConfiguration.

**Comment by heatherdaye** [comment]
After further investigation, the comma separated string works to set the multiple paths, however get-DSCConfiguration only returns the FIRST path. This causes failure when used in Azure DSC. This occurs in both Network_access_Remotely_accessible_registry_paths and Network_access_Remotely_accessible_registry_paths_and_subpaths

**Comment by johlju** [comment]
Okay! Relabelling this as a bug then. 🙂

**Comment by dancs85** [comment]
@jcwalker It looks like you are dropping the first item in the array (which contains valid data): https://github.com/PowerShell/SecurityPolicyDsc/blob/543df7a2007b5594ee274feae4da7609b96dc9f7/DSCResources/MSFT_SecurityOption/MSFT_SecurityOption.psm1#L58
Is this intended?

**Comment by jcwalker** [comment]
Closing this as it was correct it [PR#111](https://github.com/PowerShell/SecurityPolicyDsc/pull/111)
