### ISSUE TITLE
how to export security policy to a file and restore from it?

### ISSUE THREAD

**Issue by hoyeunglee** [PowerShell/SecurityPolicyDsc#91]
https://blogs.msdn.microsoft.com/powershell/2017/02/21/managing-security-settings-on-nano-server-with-dsc/

after read above article, there are two AuditPolicyDsc, SecurityPolicyDSC

but gpedit has only one, i am little confused, are audit policy and security policy are two different setting?

how to export security policy to a file and restore from it?

if export to a file, check the exported file to check whether policy applied or use SecurityPolicyDSC to validate the policy whether is applied?

**Comment by johlju** [comment]
Yes, [AuditPolicyDsc](https://github.com/PowerShell/AuditPolicyDsc/) and SecurityPolicyDsc sets different settings.

You have to build a DSC configuration file (containing you choosen baseline) that is run on each target node. See the examples folder in this repository.

**Comment by johlju** [comment]
You could possibly run Get-DscConfiguration with a configuration on a target node to get the current status of each property, from that you could build the configuration manually. Essentially "Reverse Dsc".
