### ISSUE TITLE
Set-TargetResource fails for array based security option if not already configured

### ISSUE THREAD

**Issue by russelltomkins** [PowerShell/SecurityPolicyDsc#92]
Set-TargetResource will fail to succeed if an array based security option is passed but there is no corresponding value already present in the $currentSecurityOptions dictionary object. Found whilst testing with Kerberos ETypes which isn't configured by default in the OS.

Cannot bind argument to parameter 'ReferenceObject' because it is null.
  + CategoryInfo          : InvalidData: (:) [], CimException

Simply adding another if clause to simply return false if the security option is missing from the $currentSecurityOptions resolves the issue.

Line 1031 of MSFT_SecurityOption.psm1
```
if ( $desiredSecurityOptionValue -is [array] )
            {
                If ( $currentSecurityOptions[$policy] )
                {
                    $compareResult = Compare-Array -ReferenceObject $currentSecurityOptions[$policy] -DifferenceObject $desiredSecurityOptionValue

                    if ( -not $compareResult )
                    {
                        return $false
                    }
                }
                else 
                { 
                    return $false
                }
            }
```

**Comment by johlju** [comment]
@russelltomkins Are you about to fix this too in the PR that you are about to send it?

**Comment by russelltomkins** [comment]
I do have a fix (as above), but another having another quick look at the parent condition loop I think there maybe another bug

**Comment by rsteenwyk** [comment]
@russelltomkins curious if you are still looking at this? This bit me today and @indented-automation helped me track it down to here.
